### PR TITLE
[Gallery] feat: Added onZoomBegin and onZoomEnd callbacks for gallery

### PR DESCRIPTION
**Pull request by HadesShadows**
I was the one who raised the issue, this is a code that I have written for gallery. I have not used other components therefore not added these callback support there as I haven't seen the code

These callbacks will support `index: number` to allow developers to have more control on the zoom event

### What is added?

| Name | Type | Default | Description|
|--------|------|---------|--------------|
| onZoomBegin | `(index: number) => void` | `undefined` | Callback triggered when component is zoomed. |
| onZoomEnd | `(index: number) => void` | `undefined` | Callback triggered when component returns back to original state. |

### How it works? 

```javascript  
useAnimatedReaction(
    () => scale.value,
    (value, previousValue) => {
      if (value !== 1 && !hasZoomed.value) { //if the value != 1, that means it is not in default state
        hasZoomed.value = true;
        onZoomBegin && runOnJS(onZoomBegin)(activeIndex.value);
      } else if (value === 1 && previousValue !== 1 && hasZoomed.value) { 
        /* 
          when the component is initally rendered, the value will be 1 and prevValue
            will not be 1, this condition will be true, and onZoomEnd() will be triggered
            to counter that, hasZoomed is used 
        */
        hasZoomed.value = false;
        onZoomEnd && runOnJS(onZoomEnd)(activeIndex.value);
      }
    },
    [scale]
  );
```

Note: I haven't tested the code snippet in iOS since I don't have macOS, but it is working as expected in android

### CODE REVIEW

**Comment by Glazzes** [comment]
Hi there, I'll not have time to review and test your changes until monday because of personal reasons, but I will be sure to test it as soon as I can.

**Comment by HadesShadows** [comment]
No Problem, take your time

**Comment by cw-nikhilnaik** [comment]
Whats the status on the pr?

**Comment by Glazzes** [comment]
@cw-nikhilnaik Pending, I've been working on another issue these days and personal issues are a thing aswell.

**Comment by Glazzes** [comment]
@HadesShadows Hi there, I just tested your changes against one of the newest features I've made and it works pretty well with it, I'm merging it 👍

I will release a new version soon!

**Pull request merged**
